
version: "3.9"
services:
  gameserver:
    image: game-server-image:latest
    container_name: game-server
    restart: "no"
    networks:
      - shared_network
    ports:
      - ":1234"   # host:container

  partition:
    image: partition-image:latest
    container_name: partition
    restart: "no"
    networks:
      - shared_network
    ports:
      - "1235:1234"   # host:container

networks:
  shared_network:
    driver: bridge

